CREATE DATABASE Cursos;
GO

USE Cursos;
GO

-- TABELA ÁREA
CREATE TABLE Area(
    IdArea VARCHAR(40) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL
);

-- TABELA CURSO
CREATE TABLE Curso(
    IdCurso VARCHAR(40) PRIMARY KEY,
    Imagem VARCHAR(100),
    Nome VARCHAR(100) NOT NULL,
    IdArea VARCHAR(40) FOREIGN KEY REFERENCES Area(IdArea)
);

-- TABELA USUÁRIO
CREATE TABLE Usuario(
    IdUsuario VARCHAR(40) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(256) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL
);

-- CONSULTAS
SELECT * FROM Area;
SELECT * FROM Curso;
SELECT * FROM Usuario;